"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Callable

class _DbFileExistsException(Exception):
    """Exception raised when the database file already exists."""
    def __init__(self, db_filepath: Path) -> None:
        ...
    


def create_database(db_filepath: Path, init_sql: str = ...) -> None:
    ...

def create_database_pass_if_exists(db_filepath: Path, init_sql: str = ...) -> None:
    ...

class Sqlite3ConnectionProvider:
    '''Provides the connection from a path'''
    def __init__(self, db_path: str | Path, timeout: int = ...) -> None:
        ...
    


def dynamic_database_connection_closer[**__P,__T](func: Callable[__P, __T]) -> Callable[__P, __T]:
    ...

