"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Callable

def create_database(db_filepath: Path, init_sql: str | None = ...): # -> None:
    ...

class Sqlite3ConnectionProvider:
    '''Provides the connection from a path'''
    def __init__(self, db_path: str | Path, timeout: int = ...) -> None:
        ...
    


def dynamic_database_connection_closer[**__P,__T](func: Callable[__P, __T]) -> Callable[__P, __T]:
    ...

