"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from enum import Enum
from typing import Any

class DbDatatype(Enum):
    INT = ...
    REAL = ...
    TEXT = ...
    BLOB = ...
    DATETIME_TEXT = ...
    DATETIME_REAL = ...
    DATETIME_INT = ...
    BOOL = ...


class DbField:
    def __init__(self, datatype: DbDatatype, is_pk: bool = ..., default_value: Any | None = ..., name: str | None = ...) -> None:
        ...
    
    @classmethod
    def get_classname(cls) -> str:
        ...
    


class TableTemplateEnum(Enum):
    @classmethod
    def get_fields(cls) -> dict[str, DbField]:
        ...
    
    @classmethod
    @abstractmethod
    def get_row_data(cls, *args: Any, **kwargs: Any) -> dict[Any, Any]:
        ...
    


class DbTableMixin:
    @classmethod
    def get_create_table_sql(cls, table_enum: type[TableTemplateEnum], if_not_exists: bool = ...) -> str:
        ...
    


class TestColumn(DbTableMixin, TableTemplateEnum):
    ID = ...
    NAME = ...
    @classmethod
    def get_table_name(cls) -> str:
        ...
    
    @classmethod
    def insert_sql(cls, name: str) -> str:
        ...
    
    @classmethod
    def get_row_data(cls, name: str) -> dict[TestColumn, Any]:
        ...
    


